# Generated by Django 5.1.2 on 2024-10-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_audiofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('email_body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
