# Generated by Django 5.1.2 on 2024-10-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_emaillog_delete_audiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_body',
            field=models.TextField(blank=True, default='neither', max_length=15, null=True),
        ),
    ]
