# Generated by Django 5.1.2 on 2024-10-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_user_email_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email_body',
            new_name='state',
        ),
    ]
